### PR TITLE
Export next and previous event triggered by marker.next() and marker.prev()

### PR DESCRIPTION
**Pull request by weijyewang**
Just expose another 2 events and return the travel marker data.

### CODE REVIEW

**Comment by ManpreetSingh80** [comment]
Hi @weijyewang ,

Thanks for submitting the PR.

Can you remove the package-lock.json from PR. Otherwise, it looks good. I will test it in a day or two and merge it. 

After updating the dependencies (it has been a while), I will publish it to npm also.

**Review by ManpreetSingh80 — CHANGES_REQUESTED** [review]
Remove package-lock.json

**Comment by ManpreetSingh80** [comment]
This is now available in version 0.12

**Review by weijyewang — COMMENTED** [review]
Take in changes

**Pull request closed without merging**
